version: '3.8'
services:
  app:
    build: .
    environment:
      - LOG_LEVEL=debug  
    container_name: landing
    volumes:
        - .:/app
        - /app/node_modules
        # - /app/.next
    ports:
      - "3000:3000"