version: '3.8'

services:
  app:
      depends_on:
        - db
      build: ./
      links:
        - db
      command: bun s
      volumes:
        - .:/app
      ports:
        - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
      stdin_open: true
      tty: true
  db:
    build: ./db
    environment: 
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
    volumes:
      - db:/var/lib/mysql
    ports: 
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT

volumes: 
  db: