version: '3.8'

services:
  mysqldb:
    build: ./db
    environment: 
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    volumes:
      - db:/var/lib/mysql
    ports: 
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
  app:
    depends_on:
      - mysqldb
    build: ./
    links:
      - mysqldb
    command: bun s
    volumes:
      - .:/app
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    stdin_open: true
    tty: true

volumes: 
  db: