name: Deploy

on:
  push:
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:
  Development_Deploy:
    name: Build and deploy for Development
    if: github.event.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Set up bun
        uses: oven-sh/setup-bun@v1
      - name: Install and Build
        run: cd ./landing && bun install && bun run build
      - name: Deploy
        run: aws s3 sync ./landing/out s3://devhr.midstem.net

  Stage_Deploy:
    name: Build and deploy for Stage
    if: github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Set up bun
        uses: oven-sh/setup-bun@v1
      - name: Install and Build
        run: cd ./landing && bun install && bun run build
      - name: Deploy
        run: aws s3 sync ./landing/out s3://stagehr.midstem.net

  Prod_Deploy:
    name: Build and deploy for Production
    if: github.event.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Set up bun
        uses: oven-sh/setup-bun@v1
      - name: Install and Build
        run: cd ./landing && bun install && bun run build
      - name: Deploy
        run: aws s3 sync ./landing/out s3://hr.midstem.net
